apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "akto-k8s-ebpf.fullname" . }}-pod-watcher
  labels:
    {{- include "akto-k8s-ebpf.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]