apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 27017
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-mongo
