apiVersion: v2
name: akto-hybrid-redact
description: Helm chart for installing Akto
type: application
version: 1.43.0
appVersion: "1.43.0"
home: https://www.akto.io
icon: https://akto-setup.s3.amazonaws.com/templates/128x128.png
sources:
  - https://github.com/akto-api-security/helm-charts/tree/master/charts/hybrid-redact
keywords:
  - akto
  - api
  - api security
  - dast
maintainers:
  - name: Ankush Jain
    email: ankush@akto.io
