apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 1
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        kraftMetadata: shared
        deleteClaim: false
---

apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        kraftMetadata: shared
        deleteClaim: false
---

apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 4.1.1
    metadataVersion: 4.1-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      default.replication.factor: 2
      min.insync.replicas: 1
      log.retention.ms: 604800000
      log.retention.bytes: 5368709120
      log.cleanup.policy: delete
  entityOperator:
    topicOperator: {}
    userOperator: {}
---

apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: akto.api.logs
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 2
  replicas: 2
---

apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: akto.api.logs2
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 2
  replicas: 2
---

apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: akto.api.producer.logs
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 2
  replicas: 2