{{- if .Values.env.DEPLOY_DAEMONSET }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "akto-k8s-agent.fullname" . }}
  labels:
    app: akto-collector
    {{- include "akto-k8s-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: akto-collector
      app.kubernetes.io/name: {{ include "akto-k8s-agent.name" . }}
  template:
    metadata:
      labels:
        app: akto-collector
        app.kubernetes.io/name: {{ include "akto-k8s-agent.name" . }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mirror-api-logging
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AKTO_TRAFFIC_BATCH_TIME_SECS
              value: {{ .Values.env.AKTO_TRAFFIC_BATCH_TIME_SECS | quote }}
            - name: AKTO_TRAFFIC_BATCH_SIZE
              value: {{ .Values.env.AKTO_TRAFFIC_BATCH_SIZE | quote }}
            - name: AKTO_INFRA_MIRRORING_MODE
              value: {{ .Values.env.AKTO_INFRA_MIRRORING_MODE | quote }}
            - name: AKTO_KAFKA_BROKER_MAL
              value: {{ (.Values.env.AKTO_KAFKA_BROKER_MAL | default (printf "%s.%s.svc.cluster.local:9092" (default (printf "%s-mini-runtime" .Values.miniRuntimeReleaseName) .Values.miniRuntimeServiceName) .Release.Namespace)) | quote }}
            - name: AKTO_MONGO_CONN
              value: {{ .Values.env.AKTO_MONGO_CONN | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}

