{{ if .Values.keel.keel.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "akto.fullname" . }}-keel
  labels:
    app: {{ include "akto.fullname" . }}-keel
  {{- include "akto.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.keel.serviceAccount.annotations | nindent 4 }}
{{ end }}