{{- if and .Values.mini_runtime.kafka1.useSasl .Values.mini_runtime.kafka1.env.useSecretsForSaslCredentials (not .Values.mini_runtime.kafka1.env.saslCredentialsSecrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mini-runtime-sasl" (include "akto.fullname" .) }}
  labels:
    {{- include "akto.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.mini_runtime.kafka1.env.saslCredentialsSecrets.username | b64enc }}
  password: {{ .Values.mini_runtime.kafka1.env.saslCredentialsSecrets.password | b64enc }}
{{- end }}

