{{- if and .Values.kafkaCluster.enabled .Values.kafkaCluster.strimziInstall.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "akto.fullname" . }}-strimzi-installer
  labels:
    {{- include "akto.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "akto.fullname" . }}-strimzi-installer
  labels:
    {{- include "akto.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "akto.fullname" . }}-strimzi-installer
    namespace: {{ .Release.Namespace }}
{{- end }}
