{{- if .Values.mini_runtime.kafka1.useSasl }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akto.fullname" . }}-zookeeper-jaas-config
  labels:
    {{- include "akto.labels" . | nindent 4 }}
data:
  zookeeper_jaas.conf: |
    Server {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="{{ .Values.mini_runtime.zoo1.env.saslUsername }}"
      password="{{ .Values.mini_runtime.zoo1.env.saslPassword }}"
      user_{{ .Values.mini_runtime.zoo1.env.saslUsername }}="{{ .Values.mini_runtime.zoo1.env.saslPassword }}";
    };
{{- end }}
