apiVersion: v2
name: akto-threat-client
description: Helm chart for installing Akto
type: application
version: 0.2.3
appVersion: "0.2.3"
home: https://www.akto.io
icon: https://akto-setup.s3.amazonaws.com/templates/128x128.png
sources:
  - https://github.com/akto-api-security/helm-charts/tree/master/charts/threat-client
keywords:
  - akto
  - api
  - api security
  - dast
maintainers:
  - name: Ankush Jain
    email: ankush@akto.io
