{{- if .Values.persistence.enabled -}}
{{- if not .Values.persistence.existingClaim -}}
{{- range $key, $path := .Values.persistence.mountPaths }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "damn-vulnerable-mcp-server.fullname" $ }}-{{ $key }}
  labels:
    {{- include "damn-vulnerable-mcp-server.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $key }}
  {{- with $.Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ $.Values.persistence.accessMode }}
  {{- if $.Values.persistence.storageClass }}
  {{- if eq "-" $.Values.persistence.storageClass }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ $.Values.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size }}
{{- end }}
{{- end }}
{{- end }}
